### ISSUE TITLE
Sollicitatie Staff Rik de Groot. AFGEKEURD

### ISSUE THREAD

**Issue by Rikdegroot** [Roquex02/Rustroleplayunited#2]
Beste Lucas,
Dit is mijn sollicitatie voor een staff rank op jouw server.
In deze sollicitatie bespreek ik mijn goede en slechte punten.
Veel plezier/suc6 tijdens het lezen :p.

Mijn pluspunten:
Ik ben elke dag meer als 1 uur online.
Ik doe wat mijn opdrachten zijn.
Ik ben serieus als het gaat om dingen die belangrijk zijn.
Ik ben ook serieus bij vragen van spelers of andere staff leden.

Mijn iets minder goede punten:
Ik ben zonder opdracht niet heel serieus.
Ik ben een beetje druk.
Ik kan niet goed werken voor iemand als ik geen opdracht hebt.

Dat waren mijn goede/slechte punten.
dit was mijn sollicitatie,

Ps. Het was voor een mod rank.
M.V.G Rik de Groot

**Comment by Roquex02** [comment]
Beste Rik de Groot,
Bij deze ben je aangenomen als beginnende moderator. Dit houd in dat je zal worden begeleid door een aangewezen staffflid tot dat je dit helemaal onder de knie hebt (Er staat nergens in je sollicitatie iets over ervaringen met staff). Je kan beginnen op zaterdag 25 november. Mochten er nog vragen zijn? Je kan me altijd een PM sturen in de discord server.

Met vriendelijke groet,
Lucas Huls
Owner of RRPU®
