### ISSUE TITLE
Sollicitatie RRPU Rik de Groot

### ISSUE THREAD

**Issue by Rikdegroot** [Roquex02/Rustroleplayunited#3]
Beste lucas,
Dit is mijn nieuwe sollicitatie voor een Admin staff rank op jouw server. Ik maak deze sollicitatie omdat mijn vorige sollicitatie niet helemaal correct was. Onder andere dit soort fouten: Ik had niet de correcte info, en ik had niet aangeven wat ik nou eigenlijk wilde worden. En daarom is hier de 2de variant. 
Zo als ik net al zei wil ik graag Admin worden op jouw server. Ik heb een paar reden waarom je mij moet kiezen:      
1. Ik luister naar me opdrachten.
2. Ik ben goed in het leiden van projecten/taken.
3. Ik help goed mee.
4. Ik ben sociaal.
Natuurlijk heb ik zoals ieder ander mens ook minpunten. Natuurlijk probeer ik ze te verbeteren. Dit zijn mijn minpunten:
1. Zonder opdracht ben ik niet heel serieus.
2. Ik ben een beetje eigenwijs. 
3. Ik heb niet heel veel staff ervaring, Ik ben 2x mod geweest en 1x helpen. ( 1x mod en 1x helper op 1 van jouw servers.)
Ik probeer alle 3 de minpunten beter te maken. Zodat ik 7 pluspunten krijg bij mijn volgende sollicitatie.
In die paar keer dat ik staff ben geweest heb ik veel geleerd zoals: Bemoei je niet overal mee en soms moet je niet te veel ruzie zoeken. 
Dit wil ik graag doen als ik Admin ben:
1. Ik wil ervoor zorgen dat de clans allemaal eerlijk spelen. 
2. Ik wil ervoor zorgen dat de andere staff leden niet misbruik maken van hun rank.
3. Ik wil ervoor zorgen dat iedereen op de server plezier heeft. Niet alleen me vrienden.
4. Ik wil ervoor zorgen dat er een leuk staff team is.
Als jij mij Admin maak zorg ik ervoor dat deze 4 stappen uitkomen. Dat beloof ik je.
Tot snel!
RdeG
RikdeGroot.

**Comment by Roquex02** [comment]
Beste Rik de Groot,
Je hebt alle informatie in je sollicitatie die ik nodig had vernoemd. Welkom bij het staff-team je bent aangenomen als Proef-Admin dit houd gewoon in dat 1 of meer weken proef bent. Verder vragen kan je me altijd via PM 
Met vriendelijk Groet,
Lucas
Owner of RRPU
