### ISSUE TITLE
Sollicitatie Admin RRPU

### ISSUE THREAD

**Issue by TheisGeemsNL** [Roquex02/Rustroleplayunited#4]
Beste Lucas,
Mijn naam is Thijs Bakker en ik wil graag solliciteren als Admin bij uw server.
Een van mijn pluspunten is, ik ben goed in het helpen en het begeleiden van spelers die nieuw zijn op de server. Voor de rest ben ik goed in luisteren en het uitvoeren van opdrachten. Mijn minpunten zijn dat ik weinig tot geen geduld heb en ik kan op maandagavond en woensdagavond niet online zijn i.v.m mijn voetbaltraining. Ik heb veel ervaring als staff en sta klaar om te helpen als het nodig is.

M.v.g. 
Thijs Bakker
Username: TheisGeemsNL

**Comment by Roquex02** [comment]
Beste Thijs,
Je hebt alle informatie genoemd in je sollicitatie. Hierbij ben je aangenomen als Junior-Admin! Welkom in het team. Verdere vragen? Dan kan je me altijd via de PM bereiken.
Met vriendelijke Groet,
Lucas
Owner of RRPU©
