### ISSUE TITLE
Sollicitatie Mark winters (Avesti)

### ISSUE THREAD

**Issue by Avesti** [Roquex02/Rustroleplayunited#5]
# **Sollicitatie**
Dit is mijn sollicitatie bericht voor de server, ik wil dan ook even gelijk zeggen dat er spelling's fouten in kunnen zitten.
### Persoonlijke Informatie
laat ik maar beginnen bij het begin: Ik ben mark 13 jaar oud en ik woon in Enschede, ik zit op Aoc-oost een zit in de klas 2bk2, ik heb al veel ervaring met het Staff zijn en ik heb zeker van al mijn fouten geleerd, ik heb ook meegeholpen bij het opbouwen van de server.
### Waar ik wel mee wil helpen
ik help ook graag met nieuwe updates.
Ik zal ook veel mensen helpen die uitleg nodig hebben van de server ook wil ik wel helpen met het in de gaten houden van spelers zodat ze zich wel aan de regels houden, ik ga dan ook niks vertellen tegen normale spelers over hun bezittingen op de server.
### Tijd dat ik online ben & Hoe  kan je mij bereiken 
Ook kunt u mij ook bereiken via Whatsapp of op Skype.
Op Whatsapp zal ik waarschijnlijk sneller kijken.
Ik zal ook zeker laten weten wat mijn school uren zijn die ik die week heb. 
Ik kan ook meestal wel 3 á 4 uur online zijn per dag, er zijn wel uitzonderingen zoals ik kan op maandag niet online komen en dat geldt het zelfde voor woensdag.
### de laatste alinea
Als u nog vragen hebt kunt u mij gerust bereiken zoals ik al zij via: Whatsapp of Skype. U weet waarschijnlijk ook wel mijn In-Game-Name(IGN) maar als nog de naam: Avesti

                                      Mvg: Mark winters(Avesti)

**Comment by Roquex02** [comment]
## Beste Mark Winters, 
Hierbij ben je aangenomen als Junior Admin dit houd in dat je 1 of meer weken junior bent. Welkom bij het staff-team! Mogen er nog andere vragen zijn dan kan je me bereiken via de discord PM.
Met vriendelijke Groet,
Lucas
**Owner of RRPU©**
