### ISSUE TITLE
Sollicitatie xKillerBjart

### ISSUE THREAD

**Issue by xKillerBjart** [Roquex02/Rustroleplayunited#6]
# Sollicitatie xKillerBjart
Ik ben Bart Dijkstra ik ben 14 jaar oud. Ik woon in Gronau en zit op de school: Het stedelijk lyceum Kottenpark. Ik zit in de klas 1G2 en ben een jaar blijven zitten. Ik heb al veel ervaring met bouwen en ik ben al een aantal keer admin of mod geweest en eventleider. Ik heb mijn pluspunten en minpunten. Mijn minpunten zijn: Ik ben eigenwijs, ik heb niet veel geduld en ik kan niet elke avond online zijn. Mijn pluspunten zijn: Ik ben 's weekends veel online, ik ben snel bereikbaar via WhatsApp, ik kan goed bouwen en ik voer meestal mijn opdrachten snel uit. Ik ben bereikbaar via WhatsApp en Skype meestal reageer ik sneller op WhatsApp mijn nummer heeft u en mijn Skype ook. Ik ben meestal elke avond 1/2 uur online. Ik ben 's weekends ong 6 uur per dag online. Dit was mijn solicitatie geachte heer Lucas H.

Mvg, Bart Dijkstra.

**Comment by Roquex02** [comment]
Beste Bart,
Je hebt alle informatie genoemd in je sollicitatie. Hierbij ben je aangenomen als Moderator! Welkom in het team. Verdere vragen? Dan kan je me altijd via de PM bereiken.
Met vriendelijke Groet,
Lucas
Owner of RRPU©
